wallpaper {
    monitor = DP-1
    path = ~/.local/share/wallpapers/monitor-1
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.local/share/wallpapers/monitor-2
    fit_mode = cover
}

splash = false
